name: Update Ticket List

on:
  schedule:
    - cron: '*/15 * * * *'  # runs every 15 minutes
  workflow_dispatch:        # allows manual trigger

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run update script
        run: python .github/scripts/update_json.py

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add workspace/tic-id.json
          git commit -m "Update tic-id.json with new ticket" || echo "No changes to commit"
          git push
